# Generated by Django 4.2.5 on 2023-09-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('long_name', models.CharField(max_length=200)),
                ('web_page', models.CharField(max_length=200)),
                ('docket_number', models.CharField(max_length=8, unique=True)),
                ('license_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('nrc_region', models.CharField(max_length=10)),
                ('parent_company_utility_name', models.CharField(max_length=200)),
                ('licensee', models.CharField(max_length=200)),
                ('parent_company_website', models.CharField(max_length=200)),
                ('parent_company_notes', models.TextField()),
                ('reactor_and_containment_type', models.CharField(max_length=50)),
                ('steam_supplier_and_design_type', models.CharField(max_length=50)),
                ('architect_engineer', models.CharField(max_length=50)),
                ('constructor_name', models.CharField(max_length=50)),
                ('construction_permit_issued', models.DateField(null=True)),
                ('operating_license_issued', models.DateField(null=True)),
                ('commercial_operation', models.DateField(null=True)),
                ('renewed_operating_license_issued', models.DateField(null=True)),
                ('operating_license_expires', models.DateField(null=True)),
                ('subsequent_renewed_operating_license_issued', models.DateField(null=True)),
                ('licensed_mwt', models.FloatField()),
                ('capacity_mwe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('power', models.SmallIntegerField()),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactors.reactor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statusentry',
            constraint=models.UniqueConstraint(fields=('reactor', 'date'), name='reactor_and_date_unique'),
        ),
    ]
