# Generated by Django 4.2.5 on 2023-09-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='parent_company_notes',
            field=models.TextField(null=True),
        ),
    ]
