# Generated by Django 4.2.5 on 2023-09-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactors', '0002_alter_reactor_parent_company_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='long_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='short_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
